myapp/urls.py
# myapp/urls.py
from django.urls import path
from .views import *
from . import views
from django.views.generic import RedirectView

app_name = 'myapp'

urlpatterns = [ 
    path('', home_page, name='home_page'),
    path('life_graph/', life_graph, name='life_graph'),
    path('travel_graph/',travel_graph,name='travel_graph'),
    path('culture_graph/',culture_graph,name='culture_graph'),
    path('IT_graph/',IT_graph,name='IT_graph'),  
    path('sports_graph/',sports_graph,name='sports_graph'),
    path('current_graph/',current_graph,name='current_graph'),
    path('wordcloud_sports/',wordcloud_sports,name='wordcloud_sports'),
    path('wordcloud_life/',wordcloud_life,name='wordcloud_life'),
    path('wordcloud_travel/',wordcloud_travel,name='wordcloud_travel'),
    path('wordcloud_IT/',wordcloud_IT,name='wordcloud_IT'),
    path('wordcloud_current/',wordcloud_current,name='wordcloud_current'),
    path('wordcloud_culture/',wordcloud_culture,name='wordcloud_culture'),
    path('login/',login,name='login'),
    path('signup/',signup,name='signup'),
    path('get_zipped_data/', views.get_zipped_data),
    path('favicon.ico', RedirectView.as_view(url='/static/images/favicon.ico')),
    path('home_page/', home2_page, name='home2_page'),
    path('get_name_from_db', get_name_from_db, name='get_name_from_db'),
]

mysite/urls.py
# mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from myapp.views import *
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
    path('life_graph/', life_graph, name='life_graph'),
    path('travel_graph/',travel_graph,name='travel_graph'),
    path('culture_graph/',culture_graph,name='culture_graph'),
    path('IT_graph/',IT_graph,name='IT_graph'),
    path('sports_graph/',sports_graph,name='sports_graph'),
    path('current_graph/',current_graph,name='current_graph'),
    path('wordcloud_sports/',wordcloud_sports,name='wordcloud_sports'),
    path('wordcloud_life/',wordcloud_life,name='wordcloud_life'),
    path('wordcloud_travel/',wordcloud_travel,name='wordcloud_travel'),
    path('wordcloud_IT/',wordcloud_IT,name='wordcloud_IT'),
    path('wordcloud_current/',wordcloud_current,name='wordcloud_current'),
    path('wordcloud_culture/',wordcloud_culture,name='wordcloud_culture'),
]

myapp/models.py
from django.db import models

class User_Table(models.Model):
    name = models.CharField(max_length=100, primary_key=True)
    username = models.CharField(max_length=100)
    password = models.CharField(max_length=100)
    birthdate = models.DateField()

    class Meta:
        db_table='user_table'

class Main_Crawling(models.Model):
    category = models.TextField(blank=True, primary_key=True)
    title = models.TextField(blank=True, null=True)
    link = models.TextField(blank=True, null=True)
    author = models.TextField(blank=True, null=True)
    subtopic = models.TextField(blank=True, null=True)
    content = models.TextField(blank=True, null=True)
    
    class Meta:
        db_table = 'main_crawling'

myapp/views.py
# myapp/views.py
from django.conf import settings
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from matplotlib.figure import Figure
from io import BytesIO
import csv
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from matplotlib import rc
from matplotlib.ticker import MaxNLocator
import platform
import matplotlib.pyplot as plt
from PIL import Image
import re
import numpy as np
from wordcloud import WordCloud
nltk.download('stopwords')
nltk.download('averaged_perceptron_tagger')
from .models import Main_Crawling, User_Table
import json
nltk.download('punkt')
from django.contrib.auth.decorators import login_required
from .models import User_Table

def life_graph(request):
    stop_word = set(stopwords.words('english'))

    fd_category = {}

    # 지정한 카테고리로 필터링
    category = '라이프'
    
    # 데이터베이스에서 데이터를 가져온 후, 리스트 형태로 변환
    category_data_db = list(Main_Crawling.objects.filter(category=category).values())

    # category_data_db에서 category와 일치하는 데이터 선택
    category_data = [row['subtopic'] for row in category_data_db if row['category'] == category]

    tokens = [word.lower() for sublist in [word_tokenize(d) for d in category_data] for word in sublist]

    fd_category = nltk.FreqDist(tokens)

    # 그래프 출력
    if platform.system() == 'Windows':
        rc('font', family='Malgun Gothic')
    elif platform.system() == 'Darwin':  
        rc('font', family='AppleGothic')
    else:  # Linux
        rc('font', family='NanumGothic')

    fig, ax = plt.subplots(figsize=(4, 4))

    ax.plot(*zip(*fd_category.items()), linestyle='-', marker='o', markersize=4, linewidth=1, color='#FF5733')
    ax.set_title(f'{category} Category')
    ax.set_xlabel('Word')
    ax.set_ylabel('Frequency')
    plt.subplots_adjust(top=0.9, bottom=0.25, left=0.2, right=0.9)

    ax.set_xticks(range(len(fd_category)))
    ax.set_xticklabels(fd_category.keys(), rotation='vertical')
    ax.grid(linestyle="--")
    ax.set_xlim(left=0)
    ax.yaxis.set_major_locator(MaxNLocator(integer=True))
    

    plt.tight_layout()

    # Figure를 이미지로 변환
    plt.switch_backend('Agg')
    canvas = FigureCanvas(fig)
    buffer = BytesIO()
    canvas.print_png(buffer)
    plt.close(fig)

    # 이미지를 HttpResponse로 반환
    return HttpResponse(buffer.getvalue(), content_type='image/png')


def travel_graph(request):
    stop_word = set(stopwords.words('english'))

    fd_category = {}

    # 지정한 카테고리로 필터링
    category = '여행'
    
    # 데이터베이스에서 데이터를 가져온 후, 리스트 형태로 변환
    category_data_db = list(Main_Crawling.objects.filter(category=category).values())

    # category_data_db에서 category와 일치하는 데이터 선택
    category_data = [row['subtopic'] for row in category_data_db if row['category'] == category]

    tokens = [word.lower() for sublist in [word_tokenize(d) for d in category_data] for word in sublist]

    fd_category = nltk.FreqDist(tokens)

    # 그래프 출력
    if platform.system() == 'Windows':
        rc('font', family='Malgun Gothic')
    elif platform.system() == 'Darwin':  
        rc('font', family='AppleGothic')
    else:  # Linux
        rc('font', family='NanumGothic')

    fig, ax = plt.subplots(figsize=(4, 4))

    ax.plot(*zip(*fd_category.items()), linestyle='-', marker='o', markersize=4, linewidth=1, color='#FF5733')
    ax.set_title(f'{category} Category')
    ax.set_xlabel('Word')
    ax.set_ylabel('Frequency')
    plt.subplots_adjust(top=0.9, bottom=0.25, left=0.2, right=0.9)

    ax.set_xticks(range(len(fd_category)))
    ax.set_xticklabels(fd_category.keys(), rotation='vertical')
    ax.grid(linestyle="--")
    ax.set_xlim(left=0)
    ax.yaxis.set_major_locator(MaxNLocator(integer=True))
    

    plt.tight_layout()

    # Figure를 이미지로 변환
    plt.switch_backend('Agg')
    canvas = FigureCanvas(fig)
    buffer = BytesIO()
    canvas.print_png(buffer)
    plt.close(fig)

    # 이미지를 HttpResponse로 반환
    return HttpResponse(buffer.getvalue(), content_type='image/png')

def culture_graph(request):
    stop_word = set(stopwords.words('english'))

    fd_category = {}

    # 지정한 카테고리로 필터링
    category = '문화'
    
    # 데이터베이스에서 데이터를 가져온 후, 리스트 형태로 변환
    category_data_db = list(Main_Crawling.objects.filter(category=category).values())

    # category_data_db에서 category와 일치하는 데이터 선택
    category_data = [row['subtopic'] for row in category_data_db if row['category'] == category]

    tokens = [word.lower() for sublist in [word_tokenize(d) for d in category_data] for word in sublist]

    fd_category = nltk.FreqDist(tokens)

    # 그래프 출력
    if platform.system() == 'Windows':
        rc('font', family='Malgun Gothic')
    elif platform.system() == 'Darwin':  
        rc('font', family='AppleGothic')
    else:  # Linux
        rc('font', family='NanumGothic')

    fig, ax = plt.subplots(figsize=(4, 4))

    ax.plot(*zip(*fd_category.items()), linestyle='-', marker='o', markersize=4, linewidth=1, color='#FF5733')
    ax.set_title(f'{category} Category')
    ax.set_xlabel('Word')
    ax.set_ylabel('Frequency')
    plt.subplots_adjust(top=0.9, bottom=0.25, left=0.2, right=0.9)

    ax.set_xticks(range(len(fd_category)))
    ax.set_xticklabels(fd_category.keys(), rotation='vertical')
    ax.grid(linestyle="--")
    ax.set_xlim(left=0)
    ax.yaxis.set_major_locator(MaxNLocator(integer=True))
    

    plt.tight_layout()

    # Figure를 이미지로 변환
    plt.switch_backend('Agg')
    canvas = FigureCanvas(fig)
    buffer = BytesIO()
    canvas.print_png(buffer)
    plt.close(fig)

    # 이미지를 HttpResponse로 반환
    return HttpResponse(buffer.getvalue(), content_type='image/png')

def IT_graph(request):
    stop_word = set(stopwords.words('english'))

    fd_category = {}

    # 지정한 카테고리로 필터링
    category = 'IT'
    
    # 데이터베이스에서 데이터를 가져온 후, 리스트 형태로 변환
    category_data_db = list(Main_Crawling.objects.filter(category=category).values())

    # category_data_db에서 category와 일치하는 데이터 선택
    category_data = [row['subtopic'] for row in category_data_db if row['category'] == category]

    tokens = [word.lower() for sublist in [word_tokenize(d) for d in category_data] for word in sublist]

    fd_category = nltk.FreqDist(tokens)

    # 그래프 출력
    if platform.system() == 'Windows':
        rc('font', family='Malgun Gothic')
    elif platform.system() == 'Darwin':  
        rc('font', family='AppleGothic')
    else:  # Linux
        rc('font', family='NanumGothic')

    fig, ax = plt.subplots(figsize=(4, 4))

    ax.plot(*zip(*fd_category.items()), linestyle='-', marker='o', markersize=4, linewidth=1, color='#FF5733')
    ax.set_title(f'{category} Category')
    ax.set_xlabel('Word')
    ax.set_ylabel('Frequency')
    plt.subplots_adjust(top=0.9, bottom=0.25, left=0.2, right=0.9)

    ax.set_xticks(range(len(fd_category)))
    ax.set_xticklabels(fd_category.keys(), rotation='vertical')
    ax.grid(linestyle="--")
    ax.set_xlim(left=0)
    ax.yaxis.set_major_locator(MaxNLocator(integer=True))
    

    plt.tight_layout()

    # Figure를 이미지로 변환
    plt.switch_backend('Agg')
    canvas = FigureCanvas(fig)
    buffer = BytesIO()
    canvas.print_png(buffer)
    plt.close(fig)

    # 이미지를 HttpResponse로 반환
    return HttpResponse(buffer.getvalue(), content_type='image/png')

def sports_graph(request):
    stop_word = set(stopwords.words('english'))

    fd_category = {}

    # 지정한 카테고리로 필터링
    category = '스포츠'
    
    # 데이터베이스에서 데이터를 가져온 후, 리스트 형태로 변환
    category_data_db = list(Main_Crawling.objects.filter(category=category).values())

    # category_data_db에서 category와 일치하는 데이터 선택
    category_data = [row['subtopic'] for row in category_data_db if row['category'] == category]

    tokens = [word.lower() for sublist in [word_tokenize(d) for d in category_data] for word in sublist]

    fd_category = nltk.FreqDist(tokens)

    # 그래프 출력
    if platform.system() == 'Windows':
        rc('font', family='Malgun Gothic')
    elif platform.system() == 'Darwin':  
        rc('font', family='AppleGothic')
    else:  # Linux
        rc('font', family='NanumGothic')

    fig, ax = plt.subplots(figsize=(4, 4))

    ax.plot(*zip(*fd_category.items()), linestyle='-', marker='o', markersize=4, linewidth=1, color='#FF5733')
    ax.set_title(f'{category} Category')
    ax.set_xlabel('Word')
    ax.set_ylabel('Frequency')
    plt.subplots_adjust(top=0.9, bottom=0.25, left=0.2, right=0.9)

    ax.set_xticks(range(len(fd_category)))
    ax.set_xticklabels(fd_category.keys(), rotation='vertical')
    ax.grid(linestyle="--")
    ax.set_xlim(left=0)
    ax.yaxis.set_major_locator(MaxNLocator(integer=True))
    

    plt.tight_layout()

    # Figure를 이미지로 변환
    plt.switch_backend('Agg')
    canvas = FigureCanvas(fig)
    buffer = BytesIO()
    canvas.print_png(buffer)
    plt.close(fig)

    # 이미지를 HttpResponse로 반환
    return HttpResponse(buffer.getvalue(), content_type='image/png')

def current_graph(request):
    stop_word = set(stopwords.words('english'))

    fd_category = {}

    # 지정한 카테고리로 필터링
    category = '시사'
    
    # 데이터베이스에서 데이터를 가져온 후, 리스트 형태로 변환
    category_data_db = list(Main_Crawling.objects.filter(category=category).values())

    # category_data_db에서 category와 일치하는 데이터 선택
    category_data = [row['subtopic'] for row in category_data_db if row['category'] == category]

    tokens = [word.lower() for sublist in [word_tokenize(d) for d in category_data] for word in sublist]

    fd_category = nltk.FreqDist(tokens)

    # 그래프 출력
    if platform.system() == 'Windows':
        rc('font', family='Malgun Gothic')
    elif platform.system() == 'Darwin':  
        rc('font', family='AppleGothic')
    else:  # Linux
        rc('font', family='NanumGothic')

    fig, ax = plt.subplots(figsize=(4, 4))

    ax.plot(*zip(*fd_category.items()), linestyle='-', marker='o', markersize=4, linewidth=1, color='#FF5733')
    ax.set_title(f'{category} Category')
    ax.set_xlabel('Word')
    ax.set_ylabel('Frequency')

myapp/templates/home2_page.html
{% load static %}
{% load myapp_filters %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- 문자 인코딩 및 뷰포트 설정, 제목, 스타일시트 및 폰트 링크 -->
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>T-log - Your Blog</title>
    <link rel="stylesheet" type="text/css" href="{% static 'myapp/style2.css' %}">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'myapp/favicon.ico' %}">
    <link href="https://fonts.googleapis.com/css2?family=Vina+Sans:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Bagel+Fat+One&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Dongle&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Black+Han+Sans&display=swap" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>

<body>
    <header>
        <!-- 블로그 제목 -->
        <h1>T-log</h1>
        <div class="header-buttons">
            <button id="logout">로그아웃</button>
        </div>
        <button id="welcome">환영합니다!!</button>
    </header>

    <section class="main-content">
        <div class="container">
            <div class="category-container">
                <!-- 카테고리 버튼: 라이프, 여행, 문화, IT, 스포츠, 시사 -->
                <button type="button" class="category-button" data-graph="life_graph">라이프</button>
                <button type="button" class="category-button" data-graph="travel_graph">여행</button>
                <button type="button" class="category-button" data-graph="culture_graph">문화</button>
                <button type="button" class="category-button" data-graph="IT_graph">IT</button>
                <button type="button" class="category-button" data-graph="sports_graph">스포츠</button>
                <button type="button" class="category-button" data-graph="current_graph">시사</button>
            </div>
            <div class="graph-container">
                <div class="category-pair" id="life_pair">
                    <img src="{% url 'life_graph' %}" alt="Life Graph" id="life_graph" class="graph-image">
                    <img src="{% url 'wordcloud_life' %}" alt="Word Cloud" id='life_wordcloud' class="graph-image">
                </div>
            
                <div class="category-pair" id="travel_pair">
                    <img src="{% url 'travel_graph' %}" alt="Travel Graph" id="travel_graph" class="graph-image">
                    <img src="{% url 'wordcloud_travel' %}" alt="Word Cloud" id='travel_wordcloud' class="graph-image">
                </div>
            
                <div class="category-pair" id="culture_pair">
                    <img src="{% url 'culture_graph' %}" alt="Culture Graph" id="culture_graph" class="graph-image">
                    <img src="{% url 'wordcloud_culture' %}" alt="Word Cloud" id='culture_wordcloud' class="graph-image">
                </div>
            
                <div class="category-pair" id="IT_pair">
                    <img src="{% url 'IT_graph' %}" alt="IT Graph" id="IT_graph" class="graph-image">
                    <img src="{% url 'wordcloud_IT' %}" alt="Word Cloud" id='IT_wordcloud' class="graph-image">
                </div>
            
                <div class="category-pair" id="sports_pair">
                    <img src="{% url 'sports_graph' %}" alt="Sports Graph" id="sports_graph" class="graph-image">
                    <img src="{% url 'wordcloud_sports' %}" alt="Word Cloud" id='sports_wordcloud' class="graph-image">
                </div>
            
                <div class="category-pair" id="current_pair">
                    <img src="{% url 'current_graph' %}" alt="Current Graph" id="current_graph" class="graph-image">
                    <img src="{% url 'wordcloud_current' %}" alt="Word Cloud" id='current_wordcloud' class="graph-image">
                </div>
            </div>
            <div class="data-container">
                <!-- Ajax로 받은 데이터가 들어갈 공간 -->
            </div>
        </div>
    </section>


    <footer>
        <!-- 저작권 정보 -->
        <p>&copy; 2023 Your Blog</p>
    </footer>

    <script>
        function showGraph(graphId, event) {
            // 워드 클라우드 ID는 그래프 ID에서 'graph'를 'wordcloud'로 변경하여 가정합니다.
            var wordcloudId = graphId.replace('_graph', '_wordcloud');
            var selectedGraph = document.getElementById(graphId);
            var selectedWordcloud = document.getElementById(wordcloudId);
    
            // 모든 이미지를 숨기도록 변경
            var images = document.querySelectorAll('.graph-image');
            images.forEach(function (image) {
                image.style.display = 'none';
            });
    
            // 선택된 그래프와 워드클라우드만 표시
            if (selectedGraph && selectedWordcloud) {
                selectedGraph.style.display = 'block';
                selectedWordcloud.style.display = 'block';
            }
    
            // 모든 버튼에서 .active 클래스 제거
            var buttons = document.querySelectorAll('.category-button');
            buttons.forEach(function (button) {
                button.classList.remove('active');
            });
    
            // 클릭한 버튼에만 .active 클래스 추가
            var clickedButton = event.target;
            clickedButton.classList.add('active');
            
        }
    
        window.onload = function () {
            document.addEventListener("DOMContentLoaded", function () {
                // 초기 로딩 시 이미지 숨기기
                var images = document.querySelectorAll('.graph-image');
                images.forEach(function (image) {
                    image.style.display = 'none';
                });
            });
    
            document.addEventListener("click", function (event) {
                if (event.target.classList.contains('category-button')) {
                    var graphId = event.target.getAttribute('data-graph');
                    showGraph(graphId, event);
                }
            });
        }
        $('.category-button').click(function() {
            var category = $(this).text();  // 카테고리 이름 가져오기

            $.ajax({
                url: '/get_zipped_data/',    // 뷰의 URL
                data: {
                    'category': category      // 요청에 카테고리 이름 포함
                },
                dataType: 'json',
                success: function(data) {
                    // 서버로부터 받은 응답을 사용하여 웹 페이지 업데이트
                    // 'data-container' 요소를 비운 후 새로운 내용 추가
                    $('.data-container').empty();

                    $.each(data, function(index, item) {
                        var title = item[0];
                        var link = item[1];
                        var excerpt = item[2];
                        var author = item[3];
                        var subtopic =item[4];

                        var new_content = '<div style="text-align: left;">'
                            + '<h2>' + title + '</h2>'
                            + '<p>' + excerpt + '</p>'
                            + '<p>Author: ' + author + '</p>'
                            + '<p>subtopic: '+subtopic+'</p>'
                            + '</div>'
                            + '<div style="text-align: right;">'
                            + '<button onclick="location.href=\'' + link + '\'" type="button" style="background-color: #ff9933; color: #ffffff; border-color: #ffffff;">Go to Link</button>'
                            + '</div>'
                            +'<hr>';
                        $('.data-container').append(new_content);
                    });
                }
            });
        });
       
        
            // 로그아웃 버튼 이벤트 처리
            $("#logout").on("click", function () {
                // 회원가입 페이지로 이동 또는 회원가입 모달 띄우기
                window.location.href = "/";
            });
        
    </script>
</body>
</html>

myapp/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
     <!-- 문자 인코딩 및 뷰포트 설정, 제목, 스타일시트 및 폰트 링크 -->
     <meta charset="UTF-8">
     <meta http-equiv="X-UA-Compatible" content="IE=edge">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <link rel="stylesheet" href="{% static 'myapp/login.css' %}">
     <link rel="shortcut icon" type="image/x-icon" href="{% static 'myapp/favicon.ico' %}">
     <link href="https://fonts.googleapis.com/css2?family=Vina+Sans:wght@400;700&display=swap" rel="stylesheet">
     <link href="https://fonts.googleapis.com/css2?family=Bagel+Fat+One&display=swap" rel="stylesheet">
     <link href="https://fonts.googleapis.com/css2?family=Dongle&display=swap" rel="stylesheet">
     <link href="https://fonts.googleapis.com/css2?family=Black+Han+Sans&display=swap" rel="stylesheet">
     <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
 </head>

<body>
    <header>
        <h1>T-log</h1>
    </header>
    <div id="login-container">
        <div id="login-form">
            ID<input type="text" id="username" placeholder="아이디" name="username">
            <br>
            password<input type="password" id="password" placeholder="비밀번호" name="password">
            <br>
            <button id="login-button">로그인</button> <button id="signup-button">회원가입</button>
            <br>
        </div>
    </div>

    <script>
         // 로그인 버튼 클릭 시 동작
         $("#login-button").on("click", function () {
            var username = $("#username").val();
            var password = $("#password").val();
            var csrf_token = '{{ csrf_token }}';

            // Ajax를 사용하여 서버에 로그인 요청을 보냅니다.
            $.ajax({
                url: "{% url 'myapp:login' %}",
                type: "POST",
                data: {
                    username: username,
                    password: password,
                    csrfmiddlewaretoken: csrf_token
                },
                success: function (response) {
                    if (response.success) {
                        alert("로그인 성공");
                        window.location.href = "{% url 'myapp:home2_page' %}";
                    } else {
                        alert("로그인 실패: " + response.message);
                    }
                },
                error: function (xhr, status, error) {
                    alert("로그인 요청 실패: " + error);
                }
            });
        });

        // 회원가입 버튼 클릭 시 동작
        $("#signup-button").on("click", function () {
            window.location.href = "/signup/";

        });
    </script>
</body>

</html>

myapp/templates/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'myapp/signup.css' %}">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'myapp/favicon.ico' %}">
    <link href="https://fonts.googleapis.com/css2?family=Vina+Sans:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Bagel+Fat+One&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Dongle&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Black+Han+Sans&display=swap" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>

<body>
    <header>
        <h1>T-log</h1>
    </header>

    <div id="signup-container">
        <div id ='signup-form'>
            <form id="userForm">
                <label for="name">이름:</label>
                <input type="text" id="name" name="name" required>

                <label for="username">아이디:</label>
                <input type="text" id="username" name="username" required>

                <label for="password">패스워드:</label>
                <input type="password" id="password" name="password" required>

                <label for="passwordck">패스워드 확인:</label>
                <input type="password" id="passwordck" name="passwordck" required>

                <label for="birthdate">생년월일:</label>
                <input type="date" id="birthdate" name="birthdate" required>

                <button type="button" onclick="submitForm()">가입하기</button>
            </form>
        </div>
    </div>

    <script>
        function submitForm() {
            var name = document.getElementById('name').value;
            var username = document.getElementById('username').value;
            var password = document.getElementById('password').value;
            var passwordck = document.getElementById('passwordck').value;
            var birthdate = document.getElementById('birthdate').value;

            // Ajax를 사용하여 서버에 요청을 보냅니다.
            var xhr = new XMLHttpRequest();
            xhr.open("POST", "{% url 'myapp:signup' %}", true);
            xhr.setRequestHeader("Content-Type", "application/json");
            xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
            xhr.onreadystatechange = function () {
                if (this.readyState === 4 && this.status === 200) {
                    // 서버로부터 정상적인 응답을 받았을 때, 페이지를 login.html로 이동합니다.
                    window.location.href = "{% url 'myapp:login' %}";
                } else if (this.readyState === 4) {
                    // 오류가 발생했을 때, 오류 메시지를 표시합니다.
                    alert('Signup failed: ' + this.responseText);
                }
            };
            var data = JSON.stringify({
                "name": name,
                "username": username,
                "password": password,
                "passwordck": passwordck,
                "birthdate": birthdate
            });
            xhr.send(data);
    
            // form의 서브미션을 방지합니다.
            return false;

        }
    </script>
</body>
</html>